// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

/*Base login form container*/

func BaseLogin() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main class=\"flex flex-col justify-center items-center flex-grow w-screen h-full overflow-y-scroll bg-primary element pb-2\"><div class=\"h-full w-full flex flex-col justify-start items-center md:justify-center py-28 md:py-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

/* Login form component  */

func LoginForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-full max-w-md p-8 space-y-3 rounded-xl dark:bg-gray-50 dark:text-gray-800 md:mt-0 sm:mt-6\"><h1 class=\"text-2xl font-bold text-center text-zinc-200\">Login</h1><form class=\"gap-3 justify-center items-center flex flex-col w-full h-auto\" hx-post=\"/login\" hx-include=\"[name=&#39;email&#39;], [name=&#39;pwd&#39;]\" hx-target=\"#message-login\" hx-swap=\"outerHTML\"><div class=\"space-y-1 text-sm w-full text-zinc-200\"><label for=\"email\" class=\"block dark:text-gray-600\">Email</label> <input type=\"email\" name=\"email\" id=\"email\" required=\"true\" placeholder=\"Email\" class=\"w-full px-4 py-3 rounded-md text-black shadow-md shadow-gray-600  border-2 border-slate-800 bg-yellow-50 focus:border-btnAccent focus:ring-btnAccent focus:shadow-none\" fdprocessedid=\"dpl298\"></div><div class=\"space-y-1 text-sm text-zinc-200 w-full\"><label for=\"password\" class=\"block dark:text-gray-600\">Password</label> <input type=\"password\" name=\"pwd\" id=\"password\" placeholder=\"Password\" class=\"w-full px-4 py-3 rounded-md text-black shadow-md shadow-gray-600 border-2 border-slate-800 bg-yellow-50 focus:border-btnAccent focus:ring-btnAccent focus:shadow-none\" required=\"true\" fdprocessedid=\"dthv4\"></div><button class=\"w-1/2 mt-6 p-3 text-lg rounded-lg bg-amber-200 shadow-lg bg-btnPrimary border border-2 border-gray-800 shadow shadow-md text-btnPrimaryText shadow-slate-800 hover:bg-hoverBtnPrimary hover:shadow-none transition duration-150 ease-in-out\" id=\"sing-submit\" fdprocessedid=\"1jrywc\">Submit</button><div class=\"flex w-full h-auto justify-center items-center break-all\"><p id=\"message-login\" class=\"flex justify-center items-center text-center block w-full p-3 rounded-sm text-zinc-200 dark:bg-green-600 break-all\">Sign in with your credentials.</p></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
