// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

/*Base login form container*/

func BaseLogin() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main class=\"flex flex-col justify-center items-center flex-grow w-screen h-full overflow-y-scroll bg-primary element pb-2\"><div class=\"h-full w-full flex flex-col justify-center items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

/* Login form component  */

func LoginForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-full max-w-md p-8 space-y-3 rounded-xl dark:bg-gray-50 dark:text-gray-800\"><h1 class=\"text-2xl font-bold text-center\">Login</h1><form class=\"space-y-6 justify-center items-center flex flex-col\" hx-post=\"/login\" hx-include=\"[name=&#39;email&#39;], [name=&#39;pwd&#39;]\" hx-target=\"#message-login\" hx-swap=\"innerHTML\"><div class=\"space-y-1 text-sm w-full\"><label for=\"username\" class=\"block dark:text-gray-600\">Username</label> <input type=\"text\" name=\"email\" id=\"username\" placeholder=\"Email\" class=\"w-full px-4 py-3 rounded-md dark:border-gray-300 dark:bg-gray-50 dark:text-gray-800 focus:dark:border-green-600 shadow-md shadow-gray-600\" fdprocessedid=\"dpl298\"></div><div class=\"space-y-1 text-sm w-full\"><label for=\"password\" class=\"block dark:text-gray-600\">Password</label> <input type=\"password\" name=\"pwd\" id=\"password\" placeholder=\"Password\" class=\"w-full px-4 py-3 rounded-md dark:border-gray-300 dark:bg-gray-50 dark:text-gray-800 focus:dark:border-green-600 shadow-md shadow-gray-600\" fdprocessedid=\"dthv4\"></div><button class=\"w-1/2 px-8 py-3 text-lg rounded focus:ring hover:ring focus:ring-opacity-75 bg-amber-200 dark:text-gray-50 focus:dark:ring-cyan-600 hover:dark:ring-cyan-600 border-customColor border-spacing-4 border-r-2 shadow-lg hover:bg-violet-600\" id=\"sing-submit\" fdprocessedid=\"1jrywc\">Submit</button><p id=\"message-login\" class=\"block w-full p-3 text-center rounded-sm dark:text-gray-50 dark:bg-green-600\">Sign in with your credentials.</p></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
